socorrodeus

diff --git a/.github/workflows/robot-framework.yml b/.github/workflows/robot-framework.yml
--- a/.github/workflows/robot-framework.yml
+++ b/.github/workflows/robot-framework.yml
@@ -11,49 +11,60 @@ jobs:
         - name: Checkout Repository
           uses: actions/checkout@v2
 
-        - name: Setup Python
-          uses: actions/setup-python@v2
-          with:
-            python-version: '3.x'
+        # - name: Setup Python
+        #   uses: actions/setup-python@v2
+        #   with:
+        #     python-version: '3.x'
 
-        - name: Install Dependencies
+        - name: Set up Python 3.12.1
+          uses: actions/setup-python@v3
+          with:
+            python-version: 3.12.1
+
+        - name: Install dependencies
           run: |
+            python -m pip install --upgrade pip
             pip install robotframework
             pip install robotframework-seleniumlibrary
 
-        - name: Install Google Chrome
-          run: |
-            sudo apt-get update
-            sudo apt-get install -y wget apt-transport-https
-            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
-            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
-            sudo apt-get update
-            sudo apt-get install -y google-chrome-stable
-  
-        - name: Verify webdriver-manager installation
-          run: |
-            pip show webdriver-manager || echo "webdriver-manager not found"
-            python3 -m pip install webdriver-manager  # Tentativa explícita de instalação do webdriver-manager
-  
-        - name: Setup ChromeDriver using webdriver-manager
-          run: |
-            python3 -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
-  
-        - name: Ensure ChromeDriver is executable
-          run: chmod +x /usr/local/bin/chromedriver
+        # - name: Install Dependencies
+        #   run: |
+        #     pip install robotframework
+        #     pip install robotframework-seleniumlibrary
 
-        - name: Verify Chrome Installation
-          run: |
-            which google-chrome
-            google-chrome --version
+        # - name: Install Google Chrome
+        #   run: |
+        #     sudo apt-get update
+        #     sudo apt-get install -y wget apt-transport-https
+        #     wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+        #     sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+        #     sudo apt-get update
+        #     sudo apt-get install -y google-chrome-stable
+  
+        # - name: Verify webdriver-manager installation
+        #   run: |
+        #     pip show webdriver-manager || echo "webdriver-manager not found"
+        #     python3 -m pip install webdriver-manager  # Tentativa explícita de instalação do webdriver-manager
+  
+        # - name: Setup ChromeDriver using webdriver-manager
+        #   run: |
+        #     python3 -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
+  
+        # - name: Ensure ChromeDriver is executable
+        #   run: chmod +x /usr/local/bin/chromedriver
+
+        # - name: Verify Chrome Installation
+        #   run: |
+        #     which google-chrome
+        #     google-chrome --version
 
         - name: Run Robot Framework Tests
           run: |
             robot -d results tests
-          env:
-            CHROME_BIN: /usr/bin/google-chrome
-            ROBOT_OPTIONS: "--variable BROWSER:headlesschrome --variable CHROME_OPTS:--no-sandbox --variable CHROME_OPTS:--disable-dev-shm-usage --variable CHROME_OPTS:--disable-gpu"
-          shell: bash
+          # env:
+          #   CHROME_BIN: /usr/bin/google-chrome
+          #   ROBOT_OPTIONS: "--variable BROWSER:headlesschrome --variable CHROME_OPTS:--no-sandbox --variable CHROME_OPTS:--disable-dev-shm-usage --variable CHROME_OPTS:--disable-gpu"
+          # shell: bash
           
         - name: Salvar resultados dos testes
           if: ${{ always() }}
